### ISSUE TITLE
Add upper limits to peer dependency versions

### ISSUE THREAD

**Issue by dferber90** [meteor/eslint-config-meteor#1]
You may want to introduce upper limits to your peer dependencies since new rules introduced into them through major releases can mean that the build of people using eslint-config-meteor suddenly fails linting without them doing a major upgrade of anything themselves.

This applies mostly to `eslint-plugin-meteor` and `eslint-config-airbnb`.

**Comment by dburles** [comment]
Thanks @dferber90 that's a good point. Also, I'm yet to figure out the best approach to recommend to users as far as installing all of the correct package peer dependencies, might you have any ideas on that?

**Comment by dferber90** [comment]
Mention it prominently on the Readme and in the changelog of new releases :) And `npm` warns when peer dependencies are missing after installing a plugin.. And the linter won't run successfully when some are missing, so users may consult the Readme looking for a solution.

Other than that, I wouldn't do much else. Other packages aren't doing something special here either.

**Comment by dburles** [comment]
lol yeah it's kind of awful, airbnb [does this](https://www.npmjs.com/package/eslint-config-airbnb) which works. I think we could go with something like (with versions):

`npm i --save-dev eslint babel-eslint eslint-plugin-meteor eslint-import-resolver-meteor`

followed by:

```
(
  export PKG=eslint-config-airbnb;
  npm info "$PKG@latest" peerDependencies --json | command sed 's/[\{\},]//g ; s/: /@/g' | xargs npm install --save-dev "$PKG@latest"
)
```

See: https://www.npmjs.com/package/eslint-config-airbnb

**Comment by dburles** [comment]
Then as you said, any issues that appear can be resolved by the user
