### ISSUE TITLE
 Cannot find module '@meteorjs/eslint-config-meteor'

### ISSUE THREAD

**Issue by blueyestar** [meteor/eslint-config-meteor#5]
After running
`meteor npm run lint`
I got following error
```
Cannot find module '@meteorjs/eslint-config-meteor'
Referenced from: c:\Users\abc\Documents\Projects\html\seacorn\package.json
Error: Cannot find module '@meteorjs/eslint-config-meteor'
Referenced from: c:\Users\abc\Documents\Projects\html\seacorn\package.json
    at ModuleResolver.resolve (C:\Users\abc\AppData\Roaming\npm\node_modules\eslint\lib\util\module-resolver.js:74:19)
    at resolve (C:\Users\abc\AppData\Roaming\npm\node_modules\eslint\lib\config\config-file.js:515:25)
    at load (C:\Users\abc\AppData\Roaming\npm\node_modules\eslint\lib\config\config-file.js:532:26)
    at C:\Users\abc\AppData\Roaming\npm\node_modules\eslint\lib\config\config-file.js:424:36
    at Array.reduceRight (native)
    at applyExtends (C:\Users\abc\AppData\Roaming\npm\node_modules\eslint\lib\config\config-file.js:408:28)
    at Object.load (C:\Users\abc\AppData\Roaming\npm\node_modules\eslint\lib\config\config-file.js:566:22)
    at loadConfig (C:\Users\abc\AppData\Roaming\npm\node_modules\eslint\lib\config.js:63:33)
    at getLocalConfig (C:\Users\abc\AppData\Roaming\npm\node_modules\eslint\lib\config.js:130:29)
    at Config.getConfig (C:\Users\abc\AppData\Roaming\npm\node_modules\eslint\lib\config.js:260:26)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! seacorn@ lint: `eslint .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the seacorn@ lint script 'eslint .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the seacorn package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     eslint .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs seacorn
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls seacorn
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\abc\AppData\Local\.meteor\packages\meteor-tool\1.4.4_3\mt-os.windows.x86_32\dev_bundle\.npm\_logs\2017-06-01T15_49_41_421Z-debug.log
```

**Comment by abernix** [comment]
Did you run the `meteor npm install --save-dev @meteorjs/eslint-config-meteor` command listed on the [Install instructions](https://github.com/meteor/eslint-config-meteor#install)?

Also, unfortunately, I don't think the "Peer dependencies" instruction will work properly on Windows right now because of , so you'll have to install the [dependencies listed here](https://github.com/meteor/eslint-config-meteor/blob/c0b4ee9ee59687445f86b29b73261f4cce71d045/package.json#L19-L28) manually using `meteor npm install --save-dev <package>` for each package listed.

**Comment by blueyestar** [comment]
Thanks @abernix After manually installed peer dependencies, eslint works.

**Comment by abernix** [comment]
Awesome, glad to hear that worked!  Also, I'm realizing now that I accidentally left out the link after "because of" – I was referring to https://github.com/meteor/meteor/issues/8277, but once that's resolved, I think you'll find this pain is eased.

**Comment by mizzao** [comment]
This is confusing because of the npm package [`eslint-config-meteor`](https://www.npmjs.com/package/eslint-config-meteor). Oh well, welcome to the npm wild wild west.

**Comment by dburles** [comment]
@mizzao Yeah we did originally try to get that namespace, unfortunately the author would not yield it

**Comment by abernix** [comment]
Confusing as it may be, this package ([`@meteorjs/esline-config-meteor`](https://www.npmjs.com/package/@meteorjs/eslint-config-meteor)) is now more popular on npm than the other!  Perhaps, in the future, we can reunite the two fronts.
