### ISSUE TITLE
Transfer ownership of eslint-plugin-meteor

### ISSUE THREAD

**Issue by dferber90** [meteor/eslint-config-meteor#8]
> *Note: This issue is not related to `eslint-config-meteor`*

Hello,

I am the maker and maintainer of [`eslint-plugin-meteor`](https://github.com/dferber90/eslint-plugin-meteor) which is currently getting around 50k downloads per month. I learned a lot about web development from the Meteor community and am thankful for my time there. I have since moved on to other approaches, but I'm still maintaining `eslint-plugin-meteor`. As it's been a few years since I've last used Meteor, I've lost touch with the latest Meteor developments itself so it's hard for me to know what the best decisions for `eslint-plugin-meteor` project are.

I previously also made `dferber:prerender` which was transferred over to the @meteor organisation and eventually became [`meteor/galaxy-seo-package`](https://github.com/meteor/galaxy-seo-package).

I'd therefore like to hand ownership of `eslint-plugin-meteor` over to the @meteor organisation. Is this something you are interested in?

Cheers
Dominik

**Comment by dferber90** [comment]
Any response?

**Comment by filipenevola** [comment]
Hi @dferber90, sorry for the delay.

Sure, please transfer to us.

thank you!

**Comment by dferber90** [comment]
@filipenevola That's great! As I couldn't transfer the repo to the meteor org myself (as I don't have permission to create repos in @meteor), I transferred it to you personally. You should be able to transfer it to the meteor org after accepting the transfer to your personal account

Really appreciate it!

**Comment by filipenevola** [comment]
Great, thank you for the work @dferber90

**Comment by dferber90** [comment]
I've given you write access to the package on npm as well now, so you should be able to release new versions if necessary.

Thanks again for taking over from here! ☺️
